//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fillwords.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fillwords.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_coffee_chill_pond_hd_wallpaper_uhdpaper_com_324_5_j {
            get {
                object obj = ResourceManager.GetObject("cat-coffee-chill-pond-hd-wallpaper-uhdpaper.com-324@5@j", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОТ,ТОК,СОК
        ///КТО
        ///ОТК
        ///СОК.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПИР,МОНЕТКА,ПАРТА,ЛЕС,ДЕТАЛЬ,РАБОТА,КОРЕНЬ
        ///РИПМОА
        ///АТРАНК
        ///ЛЕСПЕТ
        ///ДЕКРАБ
        ///АТОАТО
        ///ЛЬРЕНЬ
        ///.
        /// </summary>
        internal static string level10 {
            get {
                return ResourceManager.GetString("level10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МАМА,ПАПА,СЫН,ДОЧКА
        ///МПСЫ
        ///ААПН
        ///МААД
        ///АКЧО.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПИК,МАССА,ГРЕК,ЛИХО
        ///КИПМ
        ///АССА
        ///ГКЛИ
        ///РЕОХ.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АЗИЯ,ЯПОНИЯ,ВОСТОК
        ///АЯЯВ
        ///ЗИИО
        ///ПОНС
        ///ЯКОТ
        ///.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СОЛНЦЕ,МАРС,ЗВЕЗДА,ЮПИТЕР,НЛО
        ///СМЗВЮ
        ///ОАРЕП
        ///ЛНСЗИ
        ///ЕЦАДТ
        ///ОЛНРЕ.
        /// </summary>
        internal static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПАЛОЧНИК,ШЕЛКОПРЯД,ШИНШИЛЛА
        ///ШКИНЧ
        ///ЕЛКОО
        ///ДЯРПЛ
        ///ШНИША
        ///ИЛЛАП.
        /// </summary>
        internal static string level6 {
            get {
                return ResourceManager.GetString("level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СЛОВА,МОЗГ,РАЗУМ,ПАМЯТЬ,МЫСЛЬ
        ///СЛОВА
        ///ММРАЗ
        ///ОЫСЛУ
        ///ЗАПЬМ
        ///ГМЯТЬ
        ///.
        /// </summary>
        internal static string level7 {
            get {
                return ResourceManager.GetString("level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛЮБОВЬ,ИНТЕЛЛЕКТ,ПОЛЕ,СНЕГ,АД
        ///ЛЕЛЛД
        ///ЮТПЕА
        ///БНОКТ
        ///ОИЛЕС
        ///ВЬГЕН.
        /// </summary>
        internal static string level8 {
            get {
                return ResourceManager.GetString("level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДЫМ,ЭКЗАМЕН,ПИСЬМО,КИОСК,МЫЛО
        ///КДЫМН
        ///ИЗАМЕ
        ///ОКЭОМ
        ///СПИСЬ
        ///КМЫЛО.
        /// </summary>
        internal static string level9 {
            get {
                return ResourceManager.GetString("level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Music {
            get {
                return ResourceManager.GetStream("Music", resourceCulture);
            }
        }
    }
}
